### PR TITLE
Fix data path permission

### PR DESCRIPTION
**Pull request by einverne**

### CODE REVIEW

**Comment by wiserain** [comment]
Do you think this is really necessary? Because we don't even know what would be and how many files in ```/data```. If there's millions of small files, it will change ownership of them every container restart.

**Comment by einverne** [comment]
Oh, sorry. I have to mention my problem here. When I start this container, I see log error show it cannot write to /data path, because it doesn't have the permission to write.

image



```
➜ sudo docker run -d \
    --name=flexget1 \
    -p 3549:3539 \
    -v /home/mi/Documents/flexget1/data:/data \
    -v /home/mi/Documents/flexget1/config:/config \
    -e FG_WEBUI_PASSWD=password \
    -e FG_LOG_LEVEL=info \
    -e PUID=1000 \
    -e PGID=1000 \
    -e TZ=Asia/Shanghai \
    wiserain/flexget
```

**Comment by wiserain** [comment]
Oh, I see the problem. I will make further changes after merge this PR.

**Comment by einverne** [comment]
Thank you for following up. And thank you for this great image. Thanks. :)

**Pull request merged**
